Traceback (most recent call last):
  File "/afs/crc.nd.edu/user/y/ypeng4/pycharm-community-2022.3.3/plugins/python-ce/helpers/pydev/pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/afs/crc.nd.edu/user/y/ypeng4/pycharm-community-2022.3.3/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/afs/crc.nd.edu/user/y/ypeng4/nnUNet/nnunetv2/run/run_training.py", line 306, in <module>
    run_training_entry()
  File "/afs/crc.nd.edu/user/y/ypeng4/nnUNet/nnunetv2/run/run_training.py", line 300, in run_training_entry
    run_training(args.dataset_name_or_id, args.configuration, args.fold, args.tr, args.p, args.pretrained_weights,
  File "/afs/crc.nd.edu/user/y/ypeng4/nnUNet/nnunetv2/run/run_training.py", line 231, in run_training
    nnunet_trainer.run_training(dataset_id=dataset_id)
  File "/afs/crc.nd.edu/user/y/ypeng4/nnUNet/nnunetv2/training/nnUNetTrainer/brainTrainer.py", line 121, in run_training
    self.on_train_start()
  File "/afs/crc.nd.edu/user/y/ypeng4/nnUNet/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 902, in on_train_start
    self.initialize()
  File "/afs/crc.nd.edu/user/y/ypeng4/nnUNet/nnunetv2/training/nnUNetTrainer/brainTrainer.py", line 583, in initialize
    self.network = self.build_network_architecture(self.plans_manager, self.dataset_json,
  File "/afs/crc.nd.edu/user/y/ypeng4/nnUNet/nnunetv2/training/nnUNetTrainer/brainTrainer.py", line 88, in build_network_architecture
    return get_network_from_plans(plans_manager, dataset_json, configuration_manager,
  File "/afs/crc.nd.edu/user/y/ypeng4/nnUNet/nnunetv2/utilities/get_network_from_plans.py", line 27, in get_network_from_plans
    dim = len(configuration_manager.configuration.architecture.arch_kwargs.conv_kernel_sizes[0])
AttributeError: 'dict' object has no attribute 'architecture'