<class 'nnunetv2.training.network.model.waveunet.unet.UNet'>
====================<class 'nnunetv2.training.network.model.waveunet.unet.UNet'>====================
lr: 0.01
ds wegihts: [0.50393701 0.2519685  0.12598425 0.06299213 0.03149606 0.01574803
 0.00787402]
This is the configuration used by this training:
Configuration name: 2d
 {'data_identifier': 'nnUNetPlans_2d', 'preprocessor_name': 'DefaultPreprocessor', 'batch_size': 49, 'patch_size': [256, 256], 'median_image_size_in_voxels': [256.0, 256.0], 'spacing': [1.0, 1.0], 'normalization_schemes': ['ZScoreNormalization'], 'use_mask_for_norm': [False], 'UNet_class_name': 'PlainConvUNet', 'UNet_base_num_features': 32, 'n_conv_per_stage_encoder': [2, 2, 2, 2, 2, 2, 2], 'n_conv_per_stage_decoder': [2, 2, 2, 2, 2, 2], 'num_pool_per_axis': [6, 6], 'pool_op_kernel_sizes': [[1, 1], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2]], 'conv_kernel_sizes': [[3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3]], 'unet_max_num_features': 512, 'resampling_fn_data': 'resample_data_or_seg_to_shape', 'resampling_fn_seg': 'resample_data_or_seg_to_shape', 'resampling_fn_data_kwargs': {'is_seg': False, 'order': 3, 'order_z': 0, 'force_separate_z': None}, 'resampling_fn_seg_kwargs': {'is_seg': True, 'order': 1, 'order_z': 0, 'force_separate_z': None}, 'resampling_fn_probabilities': 'resample_data_or_seg_to_shape', 'resampling_fn_probabilities_kwargs': {'is_seg': False, 'order': 1, 'order_z': 0, 'force_separate_z': None}, 'batch_dice': True}
These are the global plan.json settings:
 {'dataset_name': 'Dataset003_Cirrus', 'plans_name': 'nnUNetPlans', 'original_median_spacing_after_transp': [1.0, 1.0, 1.0], 'original_median_shape_after_transp': [128, 256, 256], 'image_reader_writer': 'SimpleITKIO', 'transpose_forward': [0, 1, 2], 'transpose_backward': [0, 1, 2], 'experiment_planner_used': 'ExperimentPlanner', 'label_manager': 'LabelManager', 'foreground_intensity_properties_per_channel': {'0': {'max': 169.0, 'mean': 40.45668029785156, 'median': 36.0, 'min': 0.0, 'percentile_00_5': 9.0, 'percentile_99_5': 106.0, 'std': 19.84197998046875}}}
2024-03-05 16:45:53.976902: unpacking dataset...
2024-03-05 16:46:06.118401: unpacking done...
2024-03-05 16:46:06.121348: do_dummy_2d_data_aug: False
2024-03-05 16:46:06.123741: Using splits from existing split file: /afs/crc.nd.edu/user/y/ypeng4/data/preprocessed_data/Dataset003_Cirrus/splits_final.json
2024-03-05 16:46:06.125230: The split file contains 3 splits.
2024-03-05 16:46:06.126311: Desired fold for training: 0
2024-03-05 16:46:06.127290: This split has 16 training and 8 validation cases.
==================batch size: 2===================
2024-03-05 16:46:06.218151: Unable to plot network architecture:
2024-03-05 16:46:06.219430: No module named 'hiddenlayer'
lr: 0.01
2024-03-05 16:46:06.271090:
2024-03-05 16:46:06.272099: Epoch 0
2024-03-05 16:46:06.273290: start training, 250
2024-03-05 16:46:06.274324: learning rate: 0.01
using pin_memory on device 0
2024-03-05 16:46:22.134382: finished training
2024-03-05 16:46:22.318010: Using splits from existing split file: /afs/crc.nd.edu/user/y/ypeng4/data/preprocessed_data/Dataset003_Cirrus/splits_final.json
2024-03-05 16:46:22.320954: The split file contains 3 splits.
2024-03-05 16:46:22.322145: Desired fold for training: 0
2024-03-05 16:46:22.323466: This split has 16 training and 8 validation cases.
2024-03-05 16:46:33.380470: predicting TRAIN001_Cirrus took 11.05 s
2024-03-05 16:46:45.463651: predicting TRAIN002_Cirrus took 9.82 s
2024-03-05 16:46:56.980046: predicting TRAIN003_Cirrus took 9.53 s
2024-03-05 16:47:07.525194: predicting TRAIN004_Cirrus took 8.70 s
2024-03-05 16:47:18.001392: predicting TRAIN005_Cirrus took 8.73 s
2024-03-05 16:47:28.747714: predicting TRAIN006_Cirrus took 9.00 s
2024-03-05 16:47:39.666027: predicting TRAIN007_Cirrus took 9.12 s
2024-03-05 16:47:50.242573: predicting TRAIN008_Cirrus took 8.71 s
joblib.externals.loky.process_executor._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/afs/crc.nd.edu/user/y/ypeng4/.conda/envs/python38/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 273, in _wrap_func_call
    return func()
  File "/afs/crc.nd.edu/user/y/ypeng4/.conda/envs/python38/lib/python3.8/site-packages/joblib/parallel.py", line 588, in __call__
    return [func(*args, **kwargs)
  File "/afs/crc.nd.edu/user/y/ypeng4/.conda/envs/python38/lib/python3.8/site-packages/joblib/parallel.py", line 588, in <listcomp>
    return [func(*args, **kwargs)
  File "/afs/crc.nd.edu/user/y/ypeng4/nnUNet/nnunetv2/training/nnUNetTrainer/retinaTrainer.py", line 442, in get_score
    seg_ref, seg_ref_dict = ref_reader.read_seg(seg_fname=file_ref)
  File "/afs/crc.nd.edu/user/y/ypeng4/nnUNet/nnunetv2/imageio/simpleitk_reader_writer.py", line 115, in read_seg
    return self.read_images((seg_fname, ))
  File "/afs/crc.nd.edu/user/y/ypeng4/nnUNet/nnunetv2/imageio/simpleitk_reader_writer.py", line 37, in read_images
    itk_image = sitk.ReadImage(f)
  File "/afs/crc.nd.edu/user/y/ypeng4/.conda/envs/python38/lib/python3.8/site-packages/SimpleITK/extra.py", line 375, in ReadImage
    return reader.Execute()
  File "/afs/crc.nd.edu/user/y/ypeng4/.conda/envs/python38/lib/python3.8/site-packages/SimpleITK/SimpleITK.py", line 8430, in Execute
    return _SimpleITK.ImageFileReader_Execute(self)
RuntimeError: Exception thrown in SimpleITK ImageFileReader_Execute: /tmp/SimpleITK/Code/IO/src/sitkImageReaderBase.cxx:97:
sitk::ERROR: The file "/afs/crc.nd.edu/user/y/ypeng4/data/preprocessed_data/Dataset003_Cirrus/gt_segmentations/BRATS_088.nii.gz" does not exist.
"""
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/afs/crc.nd.edu/user/y/ypeng4/.conda/envs/python38/lib/python3.8/site-packages/joblib/parallel.py", line 1587, in _get_outputs
    yield from self._retrieve()
  File "/afs/crc.nd.edu/user/y/ypeng4/.conda/envs/python38/lib/python3.8/site-packages/joblib/parallel.py", line 1691, in _retrieve
    self._raise_error_fast()
  File "/afs/crc.nd.edu/user/y/ypeng4/.conda/envs/python38/lib/python3.8/site-packages/joblib/parallel.py", line 1726, in _raise_error_fast
    error_job.get_result(self.timeout)
  File "/afs/crc.nd.edu/user/y/ypeng4/.conda/envs/python38/lib/python3.8/site-packages/joblib/parallel.py", line 735, in get_result
    return self._return_or_raise()
  File "/afs/crc.nd.edu/user/y/ypeng4/.conda/envs/python38/lib/python3.8/site-packages/joblib/parallel.py", line 753, in _return_or_raise
    raise self._result
RuntimeError: Exception thrown in SimpleITK ImageFileReader_Execute: /tmp/SimpleITK/Code/IO/src/sitkImageReaderBase.cxx:97:
sitk::ERROR: The file "/afs/crc.nd.edu/user/y/ypeng4/data/preprocessed_data/Dataset003_Cirrus/gt_segmentations/BRATS_088.nii.gz" does not exist.